In [1]:
import numpy as np
students=np.array([[1,2,3]])
subjects=np.array([[1,2,3,4]])
marks=np.array([[55,85,35,68],
               [90,40,32,22],
               [99,66,97,51]])
students
subjects
marks

array([[55, 85, 35, 68],
       [90, 40, 32, 22],
       [99, 66, 97, 51]])

In [2]:
print(subjects.ndim)
print(marks.ndim)


2
2


In [3]:
print(subjects.size)
print(marks.size)

4
12


In [4]:
reshaped=marks.reshape(4,3)
reshaped

array([[55, 85, 35],
       [68, 90, 40],
       [32, 22, 99],
       [66, 97, 51]])

In [5]:
transpose=marks.T
transpose

array([[55, 90, 99],
       [85, 40, 66],
       [35, 32, 97],
       [68, 22, 51]])

In [6]:
np.split(subjects,1)

[array([[1, 2, 3, 4]])]

In [7]:
marks[0,0]=11
marks

array([[11, 85, 35, 68],
       [90, 40, 32, 22],
       [99, 66, 97, 51]])

In [8]:
marks[0,0]=0
marks

array([[ 0, 85, 35, 68],
       [90, 40, 32, 22],
       [99, 66, 97, 51]])